### ISSUE TITLE
Usage with optional chart types

### ISSUE THREAD

**Issue by DRoet** [victorgarciaesgi/vue-chart-3#1]
Hi, first of all thanks for this handy wrapper. Very neat that it also works with Vue 2.

Would it be possible to add support for wrapping optional chart types outside of chartjs core, for example the [matrix](https://github.com/kurkle/chartjs-chart-matrix) type for heatmaps?

**Comment by victorgarciaesgi** [comment]
Hi @DRoet !

Never used chartjs plugins but I will look at it! Do you mean type wise (ts types) or runtime wise?
Can you give me more info on how you would use it with vue-chart-3? :)

**Comment by victorgarciaesgi** [comment]
Yeah I think exporting defineChartComponent is best for both types on runtime!

**Comment by victorgarciaesgi** [comment]
For types I base my arguments on Chart.js `ChartTypeRegistry`, I think adding shims for declaring it is mandatory

**Comment by victorgarciaesgi** [comment]
@DRoet Looks like you're lucky and your plugin already provides it's own types augmentations :D
https://github.com/kurkle/chartjs-chart-matrix/blob/21562afa31f823fe6e48199f3d9054674a58a6aa/types/index.esm.d.ts#L27

**Comment by victorgarciaesgi** [comment]
It's released on `0.1.5`, tell me if it fits you :)

**Comment by DRoet** [comment]
Would you mind also exposing it as an named export?

right now this doesn't work:
```js
import { defineChartComponent } from 'vue-chart-3'
```

however using a quick test with 
```js
import vueChart from 'vue-chart-3'
vueChart.defineChartComponent()
```
it seems to render the matrix correctly! 🚀

**Comment by victorgarciaesgi** [comment]
Hmm strange! Have you tried to reload vsCode? I will look at it tomorrow i'm not on my laptop now :(

**Comment by DRoet** [comment]
no worries, seems like you only added it as an `export default`: https://github.com/victorgarciaesgi/vue-chart-3/blob/main/src/index.ts#L21

**Comment by victorgarciaesgi** [comment]
@DRoet Should be fixed now!

**Comment by DRoet** [comment]
@victorgarciaesgi awesome, would you mind publishing another release onto NPM?

**Comment by DRoet** [comment]
thanks!
