### ISSUE TITLE
Overriding peer dependency @vue/runtime-core@"> 3"

### ISSUE THREAD

**Issue by gkarwchan** [victorgarciaesgi/vue-chart-3#102]
## Error: Overriding peer dependency @vue/runtime-core@"> 3"

Cannot install on newly created Vue-3 App created by Vue-cli

## To Reproduce

1. From the Vue-cli (@vue/cli version 4.5.13) create a new application
   Choose the following:
       1. Vue version 3
       2. Vuex
       3. Sass

2. install vuetify: npm i vuetify@3.0.0-alpha.0

3. Then install vue-chart-3
`npm i vue-chart-3`

You will get this error: 

```
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @vue/runtime-core@undefined
npm WARN node_modules/@vue/runtime-core
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @vue/runtime-core@"> 3" from vue-chart-3@3.1.0
npm WARN node_modules/vue-chart-3
npm WARN   vue-chart-3@"*" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @vue/runtime-dom@undefined
npm WARN node_modules/@vue/runtime-dom
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @vue/runtime-dom@"> 3" from vue-chart-3@3.1.0
npm WARN node_modules/vue-chart-3
npm WARN   vue-chart-3@"*" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vue/runtime-dom@> 3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ghass\AppData\Local\npm-cache\_logs\2022-02-20T22_17_53_021Z-debug.log

## My system

When I try to show the existing @vue/runtime-core, it gives me this

```
npm list @vue/runtime-core


myvue3@0.1.0 C:\code\mycode\js\vue\myvue3
`-- vue@3.2.31
  `-- @vue/runtime-dom@3.2.31
    `-- @vue/runtime-core@3.2.31
```

## Version of `vue-chart-3`
3.1.0

## Version of Vue

- [x] Vue 3

**Comment by victorgarciaesgi** [comment]
That's strange! I will look at it

**Comment by victorgarciaesgi** [comment]
Can you try `3.1.1` ? :)

**Comment by gkarwchan** [comment]
Yes that worked
Thanks
