### ISSUE TITLE
docs: add chart.js peer dependency

### ISSUE THREAD

**Issue by aentwist** [victorgarciaesgi/vue-chart-3#104]
Currently, the [documentation](https://vue-chart-3.netlify.app/guide/#introduction) does not detail that `chart.js` is a peer dependency.

**Comment by aentwist** [comment]
So I see this now,

```vue
import { Chart, DoughnutController, ArcElement, Tooltip } from 'chart.js';
```

It isn't at the top of the Installation section so it is a bit confusing. Feel free to close this.

**Comment by victorgarciaesgi** [comment]
Hi! What was the problem? You find that it's not clear that it uses Chart.js behind?

**Comment by aentwist** [comment]
Yeah I couldn't tell I needed to run `npm install vue-chart-3 chart.js` at first.. just got slightly confused
