### ISSUE TITLE
Canvas tag has incorrect attributes

### ISSUE THREAD

**Issue by Gudleiv** [victorgarciaesgi/vue-chart-3#11]
Hi!
Canvas has default height and width with incorrect attribute "attrs" in DOM
`<canvas attrs="[object Object]" width="188" height="150"></canvas>`

This fix helped me https://github.com/victorgarciaesgi/vue-chart-3/pull/12

**Comment by victorgarciaesgi** [comment]
Taht's weird, for me the canvas attributes are well rendered

`<canvas id="doughnut-chart" width="720" height="720"></canvas>`

**Comment by Gudleiv** [comment]
Same problem is here https://codesandbox.io/s/demo-vue-chart-3-ugynm

**Comment by victorgarciaesgi** [comment]
@Gudleiv Ok found the problem https://v3.vuejs.org/guide/migration/render-function-api.html#_2-x-syntax-3.

I need to make 2 different render function for Vue 2 & 3

**Comment by victorgarciaesgi** [comment]
Try `0.3.5` it should be good!

**Comment by Gudleiv** [comment]
Issue solved, thank you for quick response!
