### ISSUE TITLE
[Vue warn]: Do not use built-in or reserved HTML elements as component id: Line

### ISSUE THREAD

**Issue by Oleksii14** [victorgarciaesgi/vue-chart-3#15]
Hello! Noticed one small issue while using this lib. Can you please change the chart component names to be not similar with native HTML elements?

Example
vue-chart-3/dist/index.js, line 9

`exports.LineChart = components_1.defineChartComponent('line-chart', 'line');` to be replaced by 
`exports.LineChart = components_1.defineChartComponent('line-chart', 'line-chart');`

It should fix the issue. Thanks in advance!

**Comment by Oleksii14** [comment]
![image](https://user-images.githubusercontent.com/36737084/125931378-f07fd388-6052-44f8-8491-3a286807d6ef.png)

**Comment by victorgarciaesgi** [comment]
Hi thanks for the report! 

It's published in `0.4.1` ! I made another ajustement because the second argument if for Chart.js
https://github.com/victorgarciaesgi/vue-chart-3/commit/45a467b6820dc200d9415062fba40e82424a22ea
The warning should be gone now :)
