### ISSUE TITLE
[0.5.x] Breaks unit-testing with Jest

### ISSUE THREAD

**Issue by DerYeger** [victorgarciaesgi/vue-chart-3#21]
I had no issues testing my chart components with Jest while using 0.4.12. My Jest config includes all necessary transforms (js, ts, and vue).
However, updating to 0.5.0 or any newer version breaks Jest compatibility and results in `Jest encountered an unexpected token` with the following error:

```
 ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { defineChartComponent } from './components';
                                                                                   ^^^^^^

SyntaxError: Cannot use import statement outside a module
```

in `\node_modules\vue-chart-3\dist\index.js:1`.

I guess since 0.5.x the distributed code isn't properly transformed and cannot be directly consumed by Jest, since it doesn't transform files in `node_modules`.

**Comment by victorgarciaesgi** [comment]
Hi @DerYeger you're right I noticed it too with Nuxt SSR where the code needs to be transpiled first. I tweeking the tsconfig to make it work

**Comment by DerYeger** [comment]
Ok, I'm glad it's not just me!

Thank you for your work on this project, it's awesome to finally use Chart.js 3.

**Comment by victorgarciaesgi** [comment]
I think I fixed it in `0.5.6-alpha.2` if you could test it! :D
But it's a bug that really frustrate me because fixing it means breaking all my tests, and it's all linked to a `nanoid` import :(
I'm just learning tests and i struggle with Karma/Jest

**Comment by victorgarciaesgi** [comment]
Just managed to fix the bug AND fix the tests :p 
Waiting on your feedback!

**Comment by DerYeger** [comment]
Works like a charm, thank you!

**Comment by victorgarciaesgi** [comment]
Yeaah
