### ISSUE TITLE
Unclear how to use data from props "this is undefined"

### ISSUE THREAD

**Issue by stitch** [victorgarciaesgi/vue-chart-3#23]
Hi,

I'm passing data through props as the component should just render it and not contain it. I'm unable to find a way to access these props as 'this' is not defined. It's probably me not understanding this flavor of javascript syntax.

For example:

`
    const my_labels = computed(() => {
        console.log('generating labels')
        console.log(this.chart_data)
        let labels = [];
        this.chart_data.forEach((item) => {
          for (let i = 0; i < item.data.length; i++) {
            labels.push(item.data[i].date);
          }
        });
        console.log(labels);
        return labels;
    })
`

**Comment by victorgarciaesgi** [comment]
Hi, I think you are mixing composition-api and object-api. Composition-api does not have access to `this`.
