### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by Mastercuber** [victorgarciaesgi/vue-chart-3#25]
I can't install the package with `npm` with the error message
``` bash
npm ERR! code ERESOLVE
npm ERR! Cannot destructure property 'name' of 'node' as it is null.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-08-25T12_57_41_193Z-debug.log
```
Now I just clone the repository and install it with an entry like this
``` js
"dependencies": {
    "vue-chart-3": "file:../../../vue-chart-3"
}
```

**Comment by victorgarciaesgi** [comment]
Hi, Are you sur the bug comes from `vue-chart-3`?

**Comment by Mastercuber** [comment]
Hi, no not really. It seemed for me like this is an distribution problem of the node package since I could install other packages without any errors. 
A minute ago I created an empty project and tried to install the package again with success. So maybe this was just any temporary error with node/npm.

**Comment by Mastercuber** [comment]
Therefore I will close this issue
