### ISSUE TITLE
Is Mixed Chart Types Supported ?

### ISSUE THREAD

**Issue by Manu-jayaprakash** [victorgarciaesgi/vue-chart-3#26]
As char.js documentation suggests a way of using mixed charts - https://www.chartjs.org/docs/latest/charts/mixed.html.
Is that supported here ?

**Comment by victorgarciaesgi** [comment]
Hello! No i don't think it's supported but it's a great feature to add!
I will work on a `MixedChart` component

**Comment by victorgarciaesgi** [comment]
@Manu-jayaprakash Sorry for the long wait.

After looking at it, it may be already supported! 

Just use any Chart component you want in priority, and define mixed data with the `chart-data` prop!

https://codesandbox.io/s/demo-vue-chart-3-forked-e3yz2?file=/src/App.vue
