### ISSUE TITLE
data undefined

### ISSUE THREAD

**Issue by edwardz8** [victorgarciaesgi/vue-chart-3#28]
I’m getting the data back from graphql and it’s rendering to the template no problem, but when trying to pass the data to the chart (PolarChart) I get undefined. I don't believe this is a bug -- i'm sure I'm just overlooking something -- but I also thought it could be useful to post here incase someone in the future runs into a similar issue. 

Even though i'm using Vue3 are registerables and ChartData still required like in the demo: https://codesandbox.io/s/demo-vue-chart-3-forked-e3yz2?file=/src/App.vuehttps://codesandbox.io/s/demo-vue-chart-3-forked-e3yz2?file=/src/App.vue -- i'm wondering, because in the documentation it says nothing like that is required for Vue 3.

You should be able to run the repo: https://github.com/edwardz8/vue3-hockey-graphql to see how the data is being logged in the console.

<img width="1046" alt="console-props" src="https://user-images.githubusercontent.com/25441286/132386742-6f76b0de-0d7c-4ddc-9216-73ecad2f0a31.png">

**Comment by victorgarciaesgi** [comment]
@edwardz8 Sorry for delay I was in vacations!
Do you still have the problem?

**Comment by edwardz8** [comment]
@victorgarciaesgi no worries! but last time i checked i was still getting the same error of data undefined

**Comment by edwardz8** [comment]
resolved. closing.
