### ISSUE TITLE
Line Chart Name built-in or reserved HTML element

### ISSUE THREAD

**Issue by floriankapaun** [victorgarciaesgi/vue-chart-3#3]
Hey. First of all, thanks for your great plugin. I'm using vue-chart-3 with nuxt.js which works great so far.

However, when I want to use the line chart I get the error message `[Vue warn]: Do not use built-in or reserved HTML elements as component id: Line`.

Implementation:
```
<template>
    <Line :data="testData" />
</template>

<script>
import { Line } from 'vue-chart-3'

export default {
    components: {
        Line,
    },
    ...
}
</script>
```

I think this could easily be fixed by renaming the Line Component.

**Comment by Paulsky** [comment]
Hello @floriankapaun,

I think you can fix this by naming the import. Like this:

```
<template>
    <LineChart :data="testData" />
</template>

<script>
import { Chart, LineController, LineElement, CategoryScale, LinearScale, PointElement } from 'chart.js';
import {Line as LineChart} from 'vue-chart-3';

Chart.register(LineController, LineElement, CategoryScale, LinearScale, PointElement);

export default {
    components: {
        LineChart,
    },
    ...
}
</script>
```

**Comment by victorgarciaesgi** [comment]
Thanks for the report @floriankapaun , I will make a minor release with the `LineChart` name instead of `Line`

**Comment by victorgarciaesgi** [comment]
Released in `0.2.0`!

**Comment by DRoet** [comment]
@victorgarciaesgi I agree with this change, however maybe every chart type should get the Chart suffix to keep it consistent?
`Bar -> BarChart` ?

**Comment by victorgarciaesgi** [comment]
You're right it's more consistent. I will make another breaking change release with updated names!
