### ISSUE TITLE
Dataset.hidden property not reactive

### ISSUE THREAD

**Issue by dylan-george-field** [victorgarciaesgi/vue-chart-3#33]
I can only trigger the hidden property once from true > false (vice versa) using a ref.

The chart data is updating correctly.

See the modified demo attached to the shuffle button

https://codesandbox.io/s/demo-vue-chart-3-forked-318sq?file=/src/App.vue

**Comment by germain-receeve** [comment]
Hey @victorgarciaesgi 👋 
Thanks for creating this library, it's been a life saviour for us to migrate to Chart.js 3 on Vue 2.
Sadly, we also faced the same problem since we are using custom legends outside chart.js. We toggle the visibility of dataset using the hidden property and it is not reactive :(

Any chance you have some time to look into it ? 🙏

**Comment by BITRU** [comment]
Also have problem with legend : true when onClick used custom function.
I think that answer in chartjs doc https://www.chartjs.org/docs/latest/configuration/legend.html

If     ```
options: {
        plugins: {
            legend: {
                onClick: newLegendClickHandler...
```
 need to  `const defaultLegendClickHandler = Chart.defaults.plugins.legend.onClick;`

So, default update chart can be trigered. Will that help on fixing issue?

**Comment by victorgarciaesgi** [comment]
Hi all! Sorry for the lack of updates i try to be present as possible. I didn't know why it didn't update, the watcher corretly triggers when `hidden` is modified so I though that was on Chart.js side

**Comment by victorgarciaesgi** [comment]
Great news guys, `3.0.5` released and I found the bug! :D 

It was from me, it came from a piece of code I borrowed from `vue-chartjs`

https://github.com/victorgarciaesgi/vue-chart-3/commit/af4d6b31434cd80f0410aa1f139e34e5b0c9b1aa#diff-af796a020e973df5f3ef424841c9f55fdb45d09ffac0ca4715fc0692f257b2e3R122

**Comment by germain-receeve** [comment]
Amazing, thank you so much!!

**Comment by victorgarciaesgi** [comment]
Keep me updated! I'll wait for @dylan-george-field answer too before closing because I kind of abandonned him :(

**Comment by germain-receeve** [comment]
Oh I just noticed that you only released it for `3.x`, can you also make the `2.0.5` available so I can try it out in our Vue 2 app? :)

**Comment by victorgarciaesgi** [comment]
Oh yeah sorry, I will release it right now :)

**Comment by victorgarciaesgi** [comment]
Done!

**Comment by germain-receeve** [comment]
Just tried it out, works perfectly now with `2.0.5`.
Thanks once again and have a great evening! ✨

**Comment by BITRU** [comment]
Wow, that was quick and assomme. Thank you so much!
