### ISSUE TITLE
Is it possible to use Chart.Tooltip.positioners.middle ?

### ISSUE THREAD

**Issue by kaydwithers** [victorgarciaesgi/vue-chart-3#45]
If I try to use `Chart.Tooltip.positioners` in Vue then I get an `undefined` error. Is this possible in Vue Chart 3, if so can we add a doc for it?

Below is a vanilla JS example of Chart.Tooltip.positioners.

https://jsfiddle.net/kaydwithers/py8e5sxb/

**Comment by victorgarciaesgi** [comment]
Hi @kaydwithers , hum I don't know i didn't know this feature. Did it worked before with `vue-chartjs` ? `vue-chart-3` is basically a port of vue-chartjs
