### ISSUE TITLE
How to use options

### ISSUE THREAD

**Issue by Paulsky** [victorgarciaesgi/vue-chart-3#5]
Could you please provide an example where you explain to set the chart options? Like enabling tooltips and set scales?

Thank you in advance!

**Comment by victorgarciaesgi** [comment]
@Paulsky No problem I will update the docs!

**Comment by victorgarciaesgi** [comment]
If you are using Volar on VScode, you will get props autocompletion for options

**Comment by Paulsky** [comment]
@victorgarciaesgi Thank you very much! Unfortunately, I'm not using VScode

**Comment by victorgarciaesgi** [comment]
It's done check it out! Is it enough?
