### ISSUE TITLE
Invalid module name in augmentation, module '@vue/runtime-core' cannot be found.ts(2664) after installing

### ISSUE THREAD

**Issue by sambitevidev** [victorgarciaesgi/vue-chart-3#50]
Hey @victorgarciaesgi great lib. I faced an issue after installing it in my vue@3.2.21 project

> Invalid module name in augmentation, module '@vue/runtime-core' cannot be found.ts(2664)

![image](https://user-images.githubusercontent.com/75351755/141781047-2cc36796-a3d7-4c67-8e58-58c24469bc3d.png)

When I'm uninstalling this and re-loading vscode, the issue is not there. Can you please help. thx

**Comment by victorgarciaesgi** [comment]
Hi @sambitevidev , where does the error comes from? This does not seems related to `vue-chart-3`

**Comment by victorgarciaesgi** [comment]
Yeah I have problem with `vue-demi` since `0.5.x`. 
I'm working on removing vue-demi et maintaining 2 separates branches for Vue 2 and Vue 3. It's too complex to manage deps and types for 2 vue versions

**Comment by soulsam480** [comment]
yes, I had a pleasant experience while re writing in <scrip setup>. Also the code was easy to understand, really thanks for your hard work.

**Comment by victorgarciaesgi** [comment]
Thanks a lot! I only need time I just started a new job aha

**Comment by soulsam480** [comment]
> Thanks a lot! I only need time I just started a new job aha

That's cool. Congrats

**Comment by victorgarciaesgi** [comment]
@soulsam480 New version only for Vue 3 is out. With a legacy `2.x` for Vue 2! Check out the new docs :)

**Comment by soulsam480** [comment]
Sure will check it
