### ISSUE TITLE
How to use plugins using the `defineChartComponent`

### ISSUE THREAD

**Issue by ejirocodes** [victorgarciaesgi/vue-chart-3#52]
How to use plugins using the `defineChartComponent`

After following the guide here: https://vue-chart-3.netlify.app/guide/configuration/plugins.html

```
<script lang="ts">
import { defineChartComponent } from 'vue-chart-3';
import { MatrixController, MatrixElement } from 'chartjs-chart-matrix';

Chart.register(MatrixController, MatrixElement);

const Matrix = defineChartComponent('MatrixChart', 'matrix');
</script>
```

`<MatrixChart />` is still not working in Vue template. 
Please @victorgarciaesgi can you help out. Thanks

**Comment by victorgarciaesgi** [comment]
Can you link me a reproduction on codesandbox so I can investigate? What is the error?
