### ISSUE TITLE
All charts lose height and width if dragged and option responsive = true

### ISSUE THREAD

**Issue by LovelyAndy** [victorgarciaesgi/vue-chart-3#54]
Firstly, thank you for the quick response last time!
I have been working with a drag and drop library, [VueDraggableNext](https://github.com/anish2690/vue-draggable-next) on my project and wanted to use your VueChart3 wrapper for my project. However if you have the option responsive selected and try to drag the chart the height and width are set to 0. 
I made a CodeSandbox and gave the chart a toggle to make responsive or not to show the error. Any idea why the size is being set to 0? Is there a way to set a minimum size in the options?

Anyway, cheers for the cheers for the great wrapper, this working with composition API and Typescript is a huge help; I just hope I can figure out this responsiveness error. Cheers!

https://codesandbox.io/s/draggable-charts-8uck7?file=/src/components/Chart2.vue

**Comment by victorgarciaesgi** [comment]
Hi and thanks @LovelyAndy !
I will look into this, it could be Chart.js related because I only pass the props to the chart constructor.

Try using the `styles` prop for setting width and height as a workaround!

**Comment by LovelyAndy** [comment]
Just an update to the error. This is from the Chartjs repo. Things work with a react drag n drop project, but not one with Vite. Perhaps this is where help ends at this end as well, but I figured I'd let you know how far I got with this issue. I suspect I am not the only person with a Vue3 and Vite app trying to use charts, but only time will tell😅
https://github.com/chartjs/Chart.js/issues/9875#issuecomment-975628206

**Comment by victorgarciaesgi** [comment]
@LovelyAndy Thanks for the update! Yeah you're not the first one to open bugs with Vite related bugs 😅

**Comment by LovelyAndy** [comment]
@victorgarciaesgi Yeah, I'm not too sure the potential errors that come from Vite, but I'm sure more and more people will be attempting to do what I'm doing now; hopefully they're better at debugging it than I am haha

**Comment by LovelyAndy** [comment]
@victorgarciaesgi Just wanted to give you a quick update! Looks like the fix that I was able to get them to implement (#9876 Detect detach/attach in same observation) in Chartjs has been added as of their 3.6.1 version. This should solve the issue:D

**Comment by victorgarciaesgi** [comment]
Cool thanks for the update! I can consider it closed? :)
