### ISSUE TITLE
Errors when trying to add mixed 

### ISSUE THREAD

**Issue by LovelyAndy** [victorgarciaesgi/vue-chart-3#59]
Hello,
I am trying to make  bunch of dynamic charts and am getting errors when making  a [mixed chart](https://www.chartjs.org/docs/latest/charts/mixed.html) with a bar and line chart. 
The error I get comes from using `type: Object as PropType<ChartData<"bar"> | ChartData<"line">>` when defining my PropType. I think this is due to the definition of the **ChartData** type and not having a **ChartTypeRegistry** for mixed charts.

Do you think you could add that to the registry of this library? 
If there is already a work around that I am not seeing please let me know!

Here's a quick snapshot of what my `chart-types.ts` file looks like at the moment:
![image](https://user-images.githubusercontent.com/68723584/145260333-36e4e811-9d49-4683-bf11-6f94376666d7.png)

Adding a **type** to your dataset allows you to mix charts in ChartJS, so if that variable is added to the **ChartData** type I think it would be a quick and easy fix... I think XD

I am really loving working with this wrapper and hope to hear back soon. Cheers again for quick response time so far!

**Comment by victorgarciaesgi** [comment]
Hi @LovelyAndy, i will look into the typings, maybe there is a smart way to do it! Could you make a quick codesandbox exemple based on the vue 3 demo? 😁

**Comment by LovelyAndy** [comment]
Awesome! Cheers on the detailed and fast response:D

**Comment by victorgarciaesgi** [comment]
Keep me updated, I only checked the typings part, I hope in runtime it works too :p

**Comment by MisteFr** [comment]
Hello,

It would be great if you could send an update on this one, I am trying to make a MixedChart too but I can't get this working.
The codesandbox sent in #26 doesn't exist anymore.

Thanks!

**Comment by victorgarciaesgi** [comment]
@MisteFr Sorry I didn't see your question. Basically it's really simple. 
```ts

const chartData = computed<ChartData<any>>(() => ({
      labels: ["Paris", "Nîmes", "Toulon", "Perpignan", "Autre"],
      datasets: [
        {
          type: 'bar'
          data: dataValues.value,
          backgroundColor: [
            "#77CEFF",
            "#0079AF",
            "#123E6B",
            "#97B0C4",
            "#A5C8ED",
          ],
        },
       {
          type: 'doughtnut'
          data: dataValues.value,
          backgroundColor: [
            "#77CEFF",
            "#0079AF",
            "#123E6B",
            "#97B0C4",
            "#A5C8ED",
          ],
        },
      ],
    }));
```

I will make a section in the docs, and see if I can work on a `MixedData` utils type
