### ISSUE TITLE
NPM docs: composition-api reference

### ISSUE THREAD

**Issue by gmw-web** [victorgarciaesgi/vue-chart-3#61]
In the NPM docs (https://www.npmjs.com/package/vue-chart-3) there's the following line:

> Vue 2 requires @vue/composition-api package to also be installed, to provide Vue 3's Composition API features like ref, defineComponent, computed, reactive. **_Vue composition-api plugin will install itself so no need to register it!_**

From the other documentation, I understood that the composition-api needs manual install, so the last sentence is incorrect? I guess the NPM docs need a minor update to reflect the change.

**Comment by victorgarciaesgi** [comment]
Just updated the github and site docs yesterday but it didn't updated the npm docs yet so it's normal
