### ISSUE TITLE
Access and type $refs for Chart Components using vue2 with Typescript 

### ISSUE THREAD

**Issue by Llois41** [victorgarciaesgi/vue-chart-3#64]
Hi,

I'm coming from a vue2 and want to use this library to render nice Charts. I tried the minimal example to render a `DoughnutChart` and it works fine. Now, I want to create a `ref` to see what's possible to manipulate the chart this way. I'm following [this example](https://vue-chart-3.netlify.app/guide/usage/chart-instance.html). But when I try to access `doughtnutRef.value` it shows an error and returns `undefined`.

I understand that `ref()` is using the Composition API from vue3, but in vue2 I get the ref by `this.$refs.doughnutRef`. How can I
* access the `chartInstance` using vue2
* type the `ref` correctly (following [this documentation](https://class-component.vuejs.org/guide/refs-type-extension.html)) to get autocompletion and all the nice TS stuff, since `ref()` or `ref<>` does not seem to work in vue2

Here is my component (`TotalPie.vue`):

```Vue
<template>
  <div>
    <DoughnutChart ref="doughnutRef" :chartData="testData"></DoughnutChart>
  </div>
</template>

<script lang="ts">
import Component from 'vue-class-component';
import Vue from 'vue';
import { DoughnutChart } from 'vue-chart-3';
import { Prop } from 'vue-property-decorator';

@Component({ components: { DoughnutChart } })
export default class TotalPie extends Vue {

  // type doughnutRef correctly here
  /* $refs!: {
    doughnutRef: ExtractComponentData<typeof DoughnutChart>;
  }; */

  mounted() {
    console.log(this.$refs.doughnutRef.value); //undefined
  }

  testData = {
    labels: ['Paris', 'Nîmes', 'Toulon', 'Perpignan', 'Autre'],
    datasets: [
      {
        data: [30, 40, 60, 70, 5],
        backgroundColor: ['#77CEFF', '#0079AF', '#123E6B', '#97B0C4', '#A5C8ED'],
      },
    ],
  };
}
</script>
```

Maybe I'm getting something obvious wrong but I'm very confused by the different docs (vue, vue-class-components, vue-chart-3) and my homemade mixup of all of these.

**Comment by Llois41** [comment]
So I found that I'm getting access to e.g. the `chartData` by doing 

`console.log(this.$refs.doughnutRef.chartData.labels);`

With typing `doughnutRef` as Vue (`$refs!: { doughnutRef: Vue } )` I at least get auto completion for all Vue attributes. But how can I make it specific to `DoughnutChart` to maybe also get TS support for `chartData`? Typing `doughnutRef` as `DonutChart` gives me

`'DoughnutChart' refers to a value, but is being used as a type here. Did you mean 'typeof DoughnutChart'?`

and typing it as `typeof DoughnutChart` gives me

```
Property '$refs' in type 'TotalPie' is not assignable to the same property in base type 'object & Record<never, any> & Vue'.
Type '{ doughnutRef: VueProxy<ChartPropsOptions<"doughnut">, ComponentData<"doughnut">, DefaultData<Vue>, DefaultComputed, DefaultMethods<...>, {}, {}, {}>; }' is not assignable to type '{ [key: string]: Vue | Element | (Vue | Element)[] | undefined; }'. 
Property 'doughnutRef' is incompatible with index signature.
Type 'VueProxy<ChartPropsOptions<"doughnut">, ComponentData<"doughnut">, DefaultData<Vue>, DefaultComputed, DefaultMethods<...>, {}, {}, {}>' is not assignable to type 'Vue | Element | (Vue | Element)[] | undefined'.
```

**Comment by victorgarciaesgi** [comment]
Hi @Llois41 ! 
I don't have time to look at it now, can you make a quick reproduction on codesandbox so i can look at it tomorrow? :)

Also vue-chart-3 works with Vue 2. Did you add `@vue/composition-api` and registered it?

**Comment by victorgarciaesgi** [comment]
I didn't test it with class component though. Try using the `@Ref` of vue-property-decorator

**Comment by Llois41** [comment]
Yeah no hurry, i don't have that much time today myself. Will have a look into the `@Ref`, that's a good point. Will post some example tonight. Probs for those quick reaction man ;)

**Comment by victorgarciaesgi** [comment]
Early christmas for you! Just made a demo of `vue-chart-3` using Vue 2 + class API
https://codesandbox.io/s/vue-chart-3-vue-2-class-api-f7gv1?file=/src/App.vue

There is bugs in CodeSandbox with logging Vue instances, so try it locally :)

I can also thank you because I hadn't made exemples using other component APis so I added it to the docs!

**Comment by Llois41** [comment]
Works for me, man. Appreciate the quickness, so now I don't have to deep dive into this (at least for now). I'm still quite new to Vue and using this class style syntax feels more comfortable. Now I can dive into chart-js feeling type safe!

Joyeux Noël!

**nitpick**: In the CodeSandbox code there's an unused components folder including a `test.vue` which might cause some future confusion so why not remove it? :)

**nitpick2**: `get options(): ChartOptions<'bar'> {` is the only place where you're using single quotes. Just saw this and my inner monk had to tell you :D

**probs**: Nice little website you got there ;)

**Comment by victorgarciaesgi** [comment]
Thanks a lot! :D
Aha also thank you, the source of the website is [here](https://github.com/victorgarciaesgi/vicflix) if you want!

Yeah I was just coding quickly without formatting don't worry :p

This must come from your browser, you mean in the docs website?

**Comment by Llois41** [comment]
I mean this (and all other examples in this directory): https://github.com/victorgarciaesgi/vue-chart-3/blob/main/docs/guide/examples/vue2-composition.md
The inline HTML gets rendered as text (at least using Edge or Firefox).

**Comment by victorgarciaesgi** [comment]
Displaying correctly for me on Firefox and Edge. You maybe have a proxy or vpn that blocks it
![image](https://user-images.githubusercontent.com/15092120/147271046-dcc3b011-4cc2-4a31-a027-9d28f6a09fc2.png)

**Comment by Llois41** [comment]
![grafik](https://user-images.githubusercontent.com/37102755/147271596-7c8ff06d-752c-4efb-a928-4bdd274cf6f0.png)

This is what it looks for me. Don't have a proxy or vpn running, but it's not crucial. I got what I came here for :D

**Comment by victorgarciaesgi** [comment]
You're looking at the raw version of the source of the docs website here that's normal :p

The site is here
https://vue-chart-3.netlify.app/
