### ISSUE TITLE
Dimensions need to use parseInt

### ISSUE THREAD

**Issue by ivanjaros** [victorgarciaesgi/vue-chart-3#68]
```
Invalid prop: type check failed for prop "width". Expected Number with value 100, got String with value "100". 
  at <LineChart width="100" height="100" chartData= ...
```

Sometimes the props are set directly in which case the chart needs to handle string as number on its own.

**Comment by victorgarciaesgi** [comment]
No need for parseInt. You can pass number in props just by doing `<LineChart :width='100'/>`

**Comment by ivanjaros** [comment]
i know i can, it does not mean i should be forced to use it when standard props do not require programmatic parameters.
