### ISSUE TITLE
Cannot find module cloneDeep while using nuxt3 and vue-chart-3

### ISSUE THREAD

**Issue by andreas83** [victorgarciaesgi/vue-chart-3#70]
## Describe the bug
i am not 100% sure if it's vue-chart-3 issue or nuxt,
but its clearly related to vue-chart-3 and its dependencies, because it only occurs while component (LineChart) is loaded.
This only affects the prod build not development

## To Reproduce
git clone https://github.com/andreas83/nuxt3-vue-chart-3

yarn install
yarn build
node .output/server/index.mjs
Visit page via Browser

**ERROR**

.output/server/chunks/app/server.mjs
Cannot find module .output/server/node_modules/lodash/cloneDeep' imported from .output/server/chunks/app/server.mjs

## Version of `vue-chart-3`
3.0.4

## Version of Vue

- [x] Nuxt 3

**Comment by victorgarciaesgi** [comment]
Hi thanks for the report! I will look into this when I have time. 
Nuxt 3 is still in beta so there must be things that don't work well
Did you open an issue on nuxt repo as well?

**Comment by andreas83** [comment]
i think this issue is not related to vue-chart-3 anymore, since you are not responsible on how they generate the ".output/server/chunks/app/server.mjs" 
i started a discussion at nuxt.js -> https://github.com/nuxt/framework/discussions/2582

**Comment by victorgarciaesgi** [comment]
Just released `v3.1.0` with Vite and Nuxt 3 support and an ESM build :) Tell me if this fixes it for you!

**Comment by andreas83** [comment]
thanks @victorgarciaesgi  !!!
for me it works now :+1: 

but why did it break in the first place? 

since i have now the same issue with another lib import 

`
import debounce from "lodash/debounce";
`

**Comment by victorgarciaesgi** [comment]
I replaced lodash with lodash-es. There where other additional steps to make it compatible with esm too :)
