### ISSUE TITLE
Cannot find module '@vue/runtime-dom' or its corresponding type declarations.

### ISSUE THREAD

**Issue by gregveres** [victorgarciaesgi/vue-chart-3#72]
## Describe the bug
I have a Vue 2 project that I am trying to install vue-chart-3 into. I am using Typescript. 
When I try to build, I get this error:
```ERROR in C:/Users/Greg/source/repos/SquashSpider/SquashSpider/SkyCourt.UI/ui/node_modules/vue-chart-3/types/vue.types.d.ts(1,31):
1:31 Cannot find module '@vue/runtime-dom' or its corresponding type declarations.
  > 1 | import { CSSProperties } from '@vue/runtime-dom';
      |                               ^
    2 | import { DefaultComputed, DefaultData, DefaultMethods } from 'vue/types/options';
    3 | import Vue, { VueConstructor } from 'vue';
    4 | import { ComponentRenderProxy, ComputedOptions, ExtractDefaultPropTypes, ExtractPropTypes, MethodOptions, ShallowUnwrapRef } from '@vue/composition-api';
Version: typescript 4.4.4
```
I looked up @vue/runtime-dom and it comes from Vue 3, so I was wondering if installing it was the right thing to do. It seems odd to have to install part of Vue 3 into a Vue 2 app. BTW, I am using the vue composition api plugin for Vue 2.

I see that someone else had this issue last summer and you fixed it in a 0.3 version. The solution there seemed to be for you to get vue-chart-3 to properly require the package. But again, to me that seems like the wrong approach. I just wanted to check.

BTW, I get my CSS type definitions from [CSSType](https://github.com/frenic/csstype)

## To Reproduce

*Put a reproduction link here based on this templates*

- [Template for Vue 3](https://codesandbox.io/s/demo-vue-chart-3-ugynm)
- [Template for Vue 2](https://codesandbox.io/s/vue-chart-3-vue-2-composition-api-mw54f)
- [Template for Nuxt 2](https://codesandbox.io/s/vue-chart-3-nuxt-2-mrtej)

## Version of `vue-chart-3`
2.0.3

## Version of Vue

- [ ] Vue 3
- [x] Vue 2
- [ ] Nuxt 2
- [ ] Nuxt 3

**Comment by gregveres** [comment]
I noticed that you are already using csstype in src/utils.ts. Should that be used in vue.types.ts?

**Comment by victorgarciaesgi** [comment]
Hi @gregveres ! Thanks for the report. 
That's strange because `@vue/runtime-dom` is not in the dependencies on the vue 2 version. (Check `vue2` branch) 
Do you have `skipLibCheck: true` in your tsconfig.json ?

Sorry I don't have time to get my nose in the bugs for now so i'm just blind guessing

**Comment by gregveres** [comment]
I think that’s the thing, it isn’t in the dependency list, which is why it not resolving. 

The issue seems to be that this import is getting included in v2.

**Comment by victorgarciaesgi** [comment]
Yeah I think it was a mistake if it was still in the source! I removed it you can try `2.0.4`!

**Comment by gregveres** [comment]
Excellent. That fixed it. Thank you so much for taking the time out your busy schedule to get this addressed so quickly. This is a great improvement over vue-chartjs. Thank you for your effort on this!
