### ISSUE TITLE
Pinned @vue/runtime-core and @vue/runtime-dom causes version mismatch of core Vue 3 packages

### ISSUE THREAD

**Issue by wopian** [victorgarciaesgi/vue-chart-3#79]
## Describe the bug

https://github.com/victorgarciaesgi/vue-chart-3/commit/af4d6b31434cd80f0410aa1f139e34e5b0c9b1aa changed the version resolution of `@vue/runtime-core` and `@vue/runtime-dom` from `latest` to an exact pin on `3.2.26` for both of these. If a consumer is using an older or newer version of Vue 3 (e.g `3.2.25` or `3.3.x`), then they will have two versions of these core packages bundled with mismatched feature support.

These should ideally be a `peerDependency` targeting the major version (e.g `^3.2.0`) so it will always be in line with the version of Vue used by the consumer as these are direct dependencies of the `vue@3` package.

## Version of `vue-chart-3`

v3.0.7

## Version of Vue

- [x] Vue 3
- [ ] Vue 2
- [ ] Nuxt 2
- [ ] Nuxt 3

**Comment by victorgarciaesgi** [comment]
Hi @wopian ! It's fixed in `3.0.8` :)
