### ISSUE TITLE
Vulnerability: Upgrade nanoid to version 3.1.31 or higher.

### ISSUE THREAD

**Issue by sbourouis** [victorgarciaesgi/vue-chart-3#81]
## Describe the bug
Snyk detected a vulnerability in the latest version (3.0.7) of vue-chart-3. More details here: https://security.snyk.io/vuln/SNYK-JS-NANOID-2332193

## To Reproduce

Run vulnerability check using Snyk

## Version of `vue-chart-3`
*v3.0.7

## Version of Vue

- [x] Vue 3
- [ ] Vue 2
- [ ] Nuxt 2
- [ ] Nuxt 3

**Comment by victorgarciaesgi** [comment]
Thanks for the PR! I will merge it :)
