### ISSUE TITLE
no data section in chart-instance documentation

### ISSUE THREAD

**Issue by yaron-shamul** [victorgarciaesgi/vue-chart-3#88]
hi, very nice project but I'm having a lot of troubles with the docs
[in this page](https://vue-chart-3.netlify.app/guide/usage/chart-instance.html) you did not mentioned what data to use for running the chart

**Comment by victorgarciaesgi** [comment]
Hi, that's because this page is not about data but template refs and accessing chartInstance, so data would'nt change a thing here.

There are exemples with data (here Vue 3) on the docs https://vue-chart-3.netlify.app/guide/examples/vue3.html

**Comment by yaron-shamul** [comment]
I would like to see how to use this package in video, it might be an amazing idea to make some youtube video of how-to-use.
btw I saw this example before, I think it's good,  but I do prefer using js and not ts so it's another thing I think you can do better with the doc :)

**Comment by victorgarciaesgi** [comment]
Please look better at the docs. There is 2 full exemples using just js and not TS.
https://vue-chart-3.netlify.app/guide/examples/vue2-composition.html
https://vue-chart-3.netlify.app/guide/examples/nuxt2.html

**Comment by yaron-shamul** [comment]
I saw it, it is using vue2, also wanting some more examples.
fyi i used [this helpful example](https://www.youtube.com/watch?v=zSaaZ-TP2tc&t=3s) to create my charts finally.
