### ISSUE TITLE
Vue 3 sandbox demo shows error

### ISSUE THREAD

**Issue by robert-jf-close** [victorgarciaesgi/vue-chart-3#91]
## Describe the bug
The sandbox demo for vue 3 has the following error:
`SyntaxError
Cannot use import statement outside a module
H
https://codesandbox.io/static/js/sandbox.bc9bc6db0.js:1:99953
K.evaluate
https://codesandbox.io/static/js/sandbox.bc9bc6db0.js:1:112619
ge.evaluateTranspiledModule
https://codesandbox.io/static/js/sandbox.bc9bc6db0.js:1:123001
c
https://codesandbox.io/static/js/sandbox.bc9bc6db0.js:1:112234
$csb$eval
https://ugynm.csb.app/node_modules/vue/dist/vue.cjs.js:5:19
H
https://codesandbox.io/static/js/sandbox.bc9bc6db0.js:1:99995
K.evaluate
https://codesandbox.io/static/js/sandbox.bc9bc6db0.js:1:112619
ge.evaluateTranspiledModule
https://codesandbox.io/static/js/sandbox.bc9bc6db0.js:1:123001
c
https://codesandbox.io/static/js/sandbox.bc9bc6db0.js:1:112234
$csb$eval
https://ugynm.csb.app/node_modules/vue/index.js:6:20
H
https://codesandbox.io/static/js/sandbox.bc9bc6db0.js:1:99995
K.evaluate
https://codesandbox.io/static/js/sandbox.bc9bc6db0.js:1:112619
ge.evaluateTranspiledModule
https://codesandbox.io/static/js/sandbox.bc9bc6db0.js:1:123001
c
https://codesandbox.io/static/js/sandbox.bc9bc6db0.js:1:112234
$csb$eval
/src/main.js:1
> 1 | import { createApp } from "vue";
  2 | import App from "./App.vue";
  3 | 
  4 | createApp(App).mount("#app");
View compiled
▶ 10 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.`

## To Reproduce

https://codesandbox.io/s/demo-vue-chart-3-ugynm?file=/src/App.vue

**Comment by victorgarciaesgi** [comment]
It should be fixed! Dependency bug :p
