### ISSUE TITLE
Disabled parsing option result in lost reactivity?

### ISSUE THREAD

**Issue by mehmetalianil** [victorgarciaesgi/vue-chart-3#97]
## Describe the bug

When parsing options is false, the charts do not render reactively to data.
I have a rather large data and LineChart becomes very bogged down and slow unless these are disabled. 
There isn't a manual way to update() the chart. (As far as I could find)

## To Reproduce

I am not well versed with frontend development, with apologies, I would like to share the options that I wanted to use: (Please feel free to dismiss/reject of it is a burden.)

```
chartOptions:{
        animation: false,  
        parsing: false,      // when this true, the chart CAN refresh
        interaction: {
          mode: 'nearest',
          axis: 'x',
          intersect: false
        },
        scales: {
          x: {
            //type: 'time',    This raises an error about a prerequisite. :/ unrelated.
            ticks: {
              source: 'auto',
              // Disabled rotation for performance
              maxRotation: 0,
              autoSkip: true,
            } 
          }
        }
      }
```

Actually I wanted the performance of this example here:
https://www.chartjs.org/docs/latest/samples/advanced/data-decimation.html

## Version of `vue-chart-3`
3.0.9

## Version of Vue

- [x] Vue 3
- [ ] Vue 2
- [ ] Nuxt 2
- [ ] Nuxt 3

**Comment by victorgarciaesgi** [comment]
Hmm I don't think this option is causing this on vue-chart-3 side. Those option are disabled when big array of data is used to avoid performance issues. But it should still watch the changes. There is an `update` option. With template ref you have access to the ChartInstance and you can trigger it yourself :) 

https://vue-chart-3.netlify.app/guide/usage/chart-instance.html

**Comment by victorgarciaesgi** [comment]
If you can recreate your issue in a CodeSandbox, I could investigate :)

**Comment by mehmetalianil** [comment]
I think the issue was about passing parsing: false with a dataset that is not parsed.
Then the chart is not visible, probably due to chart.js not being able to do its thing, but it fails silently.
